import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import styles from "../styles/InfoAtticHome.module.css";

import IANav from "../componets/IANav";
import InfoAtticFooter from "../componets/InfoAtticFooter";

export default function InfoAtticHome() {
  return (
    <div>
      <Head>
        <title>Info Attics Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", flexDirection: "column", minHeight: '100%' }}>
        <IANav></IANav>

        <div style={{flexGrow: '1'}}>
          <h1 className={styles.title}>欢迎进入 Info-Attics.</h1>
          <h1 className={styles.title1}>信息大观园</h1>
        </div>

        <InfoAtticFooter></InfoAtticFooter>
      </main>
    </div>
  );
}
